// ship
// designed and built by onyxpowered.
//
// Every sentence the CLI shows a person, in seven languages. Flat keys
// (dotted for grouping, not nested objects) so lookup is one property
// access. A missing translation for the active locale falls back to
// English rather than showing a raw key -- better a familiar sentence in
// the wrong language than a broken one.
//
// House style: lowercase, always -- sentence starts included -- except
// "ship" itself and its three named parts (App, Block, Vault), which stay
// capitalized wherever they appear so they read as ship's own vocabulary,
// not ordinary nouns. Genuine acronyms (CLI, IPC, PID) keep their standard
// uppercase form; that's not capitalization, it's spelling.

export const STRINGS = {
  // ---- generic ----------------------------------------------------------
  unknownCommand: {
    en: '"{cmd}" not recognized -- run "ship help" to see everything ship can do.',
    es: '"{cmd}" no reconocido -- ejecuta "ship help" para ver todo lo que ship puede hacer.',
    fr: 'commande « {cmd} » non reconnue -- lancez « ship help » pour voir tout ce que ship sait faire.',
    it: '"{cmd}" non riconosciuto -- esegui "ship help" per vedere tutto quello che ship sa fare.',
    de: '„{cmd}“ unbekannt -- führe „ship help“ aus, um zu sehen, was ship alles kann.',
    ja: '「{cmd}」というコマンドは見つかりませんでした。「ship help」を実行すると、使えるコマンドの一覧が表示されます。',
    zh: '无法识别命令 "{cmd}"。运行 "ship help" 查看 ship 支持的所有命令。',
  },
  'suggest.notRecognized': {
    en: '"{cmd}" not recognized.',
    es: '"{cmd}" no reconocido.',
    fr: 'commande « {cmd} » non reconnue.',
    it: '"{cmd}" non riconosciuto.',
    de: '„{cmd}“ unbekannt.',
    ja: '「{cmd}」というコマンドは見つかりませんでした。',
    zh: '无法识别命令 "{cmd}"。',
  },
  'suggest.maybeMeant': {
    en: 'maybe you meant:',
    es: 'quizá quisiste decir:',
    fr: 'vous vouliez peut-être dire :',
    it: 'forse intendevi:',
    de: 'vielleicht meintest du:',
    ja: 'もしかして次のコマンドですか？',
    zh: '你是不是想输入：',
  },
  'suggest.prompt': {
    en: 'enter a number to run it, or anything else to cancel',
    es: 'introduce un número para ejecutarlo, o cualquier otra cosa para cancelar',
    fr: 'entrez un numéro pour l\'exécuter, ou n\'importe quoi d\'autre pour annuler',
    it: 'inserisci un numero per eseguirlo, o qualsiasi altra cosa per annullare',
    de: 'gib eine zahl ein, um es auszuführen, oder etwas anderes zum abbrechen',
    ja: '番号を入力すると実行します。それ以外を入力するとキャンセルします',
    zh: '输入数字即可运行，输入其他内容则取消',
  },
  genericError: {
    en: 'something went wrong: {message}',
    es: 'algo salió mal: {message}',
    fr: 'une erreur est survenue : {message}',
    it: 'qualcosa è andato storto: {message}',
    de: 'etwas ist schiefgelaufen: {message}',
    ja: '問題が発生しました: {message}',
    zh: '出了点问题：{message}',
  },
  daemonNotRunning: {
    en: 'the ship daemon isn\'t running. start it with "ship daemon start", or run "ship startup" to set it up properly.',
    es: 'el daemon de ship no está en ejecución. inícialo con "ship daemon start", o ejecuta "ship startup" para configurarlo correctamente.',
    fr: 'le daemon ship n\'est pas en cours d\'exécution. démarrez-le avec « ship daemon start », ou lancez « ship startup » pour le configurer correctement.',
    it: 'il daemon di ship non è in esecuzione. avvialo con "ship daemon start", oppure esegui "ship startup" per configurarlo correttamente.',
    de: 'der ship-daemon läuft nicht. starte ihn mit „ship daemon start“, oder führe „ship startup“ aus, um ihn richtig einzurichten.',
    ja: 'ship のデーモンが起動していません。「ship daemon start」で起動するか、「ship startup」で最初から設定してください。',
    zh: 'ship 守护进程未运行。使用 "ship daemon start" 启动，或运行 "ship startup" 进行完整设置。',
  },
  'devFlags.reset': {
    en: 'dev flags: language preference reset -- this run starts fresh.',
    es: 'dev flags: preferencia de idioma restablecida -- esta ejecución empieza de cero.',
    fr: 'dev flags : préférence de langue réinitialisée -- cette exécution repart de zéro.',
    it: 'dev flags: preferenza della lingua ripristinata -- questa esecuzione riparte da zero.',
    de: 'dev flags: spracheinstellung zurückgesetzt -- dieser lauf startet neu.',
    ja: 'dev flags: 言語設定をリセットしました。今回は初回起動として実行します。',
    zh: 'dev flags：语言偏好已重置 —— 本次运行将从头开始。',
  },
  cancelled: {
    en: 'cancelled.',
    es: 'cancelado.',
    fr: 'annulé.',
    it: 'annullato.',
    de: 'abgebrochen.',
    ja: 'キャンセルしました。',
    zh: '已取消。',
  },

  // ---- startup wizard -----------------------------------------------------
  'startup.languageConfirmed': {
    en: 'language set to {language}.',
    es: 'idioma configurado en {language}.',
    fr: 'langue définie sur {language}.',
    it: 'lingua impostata su {language}.',
    de: 'sprache auf {language} eingestellt.',
    ja: '言語を{language}に設定しました。',
    zh: '语言已设置为{language}。',
  },
  'startup.enterNumber': {
    en: 'enter a number',
    es: 'introduce un número',
    fr: 'entrez un numéro',
    it: 'inserisci un numero',
    de: 'gib eine zahl ein',
    ja: '番号を入力してください',
    zh: '请输入数字',
  },
  'startup.invalidChoice': {
    en: 'that\'s not one of the options above -- try again.',
    es: 'esa no es una de las opciones anteriores; inténtalo de nuevo.',
    fr: 'ce n\'est pas l\'une des options ci-dessus -- réessayez.',
    it: 'questa non è una delle opzioni indicate sopra: riprova.',
    de: 'das ist keine der oben genannten optionen -- versuch es noch einmal.',
    ja: '上記の選択肢の中から選んでください。もう一度お試しください。',
    zh: '这不是上面列出的选项，请重新输入。',
  },
  'startup.runModeQuestion': {
    en: 'how should ship\'s daemon run?',
    es: '¿cómo debería ejecutarse el daemon de ship?',
    fr: 'comment le daemon ship doit-il fonctionner ?',
    it: 'come dovrebbe essere eseguito il daemon di ship?',
    de: 'wie soll der ship-daemon laufen?',
    ja: 'ship のデーモンをどのように実行しますか？',
    zh: 'ship 守护进程应该以哪种方式运行？',
  },
  'startup.runModeForeground': {
    en: 'foreground -- stays attached to this terminal, easiest for trying ship out',
    es: 'primer plano: permanece conectado a esta terminal, lo más fácil para probar ship',
    fr: 'premier plan -- reste rattaché à ce terminal, le plus simple pour découvrir ship',
    it: 'primo piano: resta collegato a questo terminale, il modo più semplice per provare ship',
    de: 'vordergrund -- bleibt an dieses terminal gebunden, am einfachsten, um ship auszuprobieren',
    ja: 'フォアグラウンド — このターミナルに接続したまま動作します。まず試してみるのに最適です',
    zh: '前台运行 —— 保持连接在当前终端，最适合先体验一下 ship',
  },
  'startup.runModeBackground': {
    en: 'background -- installed as a system service, keeps running after you close this terminal or restart your machine',
    es: 'segundo plano: se instala como un servicio del sistema y sigue funcionando aunque cierres esta terminal o reinicies tu equipo',
    fr: 'arrière-plan -- installé comme service système, continue de fonctionner même après la fermeture de ce terminal ou un redémarrage',
    it: 'sfondo: installato come servizio di sistema, continua a funzionare anche dopo aver chiuso questo terminale o riavviato il computer',
    de: 'hintergrund -- als systemdienst installiert, läuft weiter, auch wenn du dieses terminal schließt oder deinen rechner neu startest',
    ja: 'バックグラウンド — システムサービスとして登録され、このターミナルを閉じたりマシンを再起動したりしても動作し続けます',
    zh: '后台运行 —— 作为系统服务安装，即使关闭此终端或重启电脑也会持续运行',
  },
  'startup.startingForeground': {
    en: 'starting the ship daemon in the foreground...',
    es: 'iniciando el daemon de ship en primer plano...',
    fr: 'démarrage du daemon ship au premier plan...',
    it: 'avvio del daemon di ship in primo piano...',
    de: 'der ship-daemon wird im vordergrund gestartet …',
    ja: 'ship のデーモンをフォアグラウンドで起動しています…',
    zh: '正在前台启动 ship 守护进程……',
  },
  'startup.startingBackground': {
    en: 'installing the ship daemon as a background service...',
    es: 'instalando el daemon de ship como servicio en segundo plano...',
    fr: 'installation du daemon ship en tant que service en arrière-plan...',
    it: 'installazione del daemon di ship come servizio in background...',
    de: 'der ship-daemon wird als hintergrunddienst installiert …',
    ja: 'ship のデーモンをバックグラウンドサービスとしてインストールしています…',
    zh: '正在将 ship 守护进程安装为后台服务……',
  },
  'startup.done': {
    en: 'all set -- ship is ready.',
    es: 'todo listo: ship está preparado.',
    fr: 'c\'est prêt -- ship est opérationnel.',
    it: 'tutto pronto: ship è operativo.',
    de: 'fertig -- ship ist einsatzbereit.',
    ja: '準備が整いました。ship は使用可能です。',
    zh: '一切就绪 —— ship 已准备好。',
  },

  // ---- version ------------------------------------------------------------
  versionLine: {
    en: 'ship {version} ({source})',
    es: 'ship {version} ({source})',
    fr: 'ship {version} ({source})',
    it: 'ship {version} ({source})',
    de: 'ship {version} ({source})',
    ja: 'ship {version}（{source}）',
    zh: 'ship {version}（{source}）',
  },
  sourceDaemon: {
    en: 'reported by the running daemon',
    es: 'informado por el daemon en ejecución',
    fr: 'communiqué par le daemon en cours d\'exécution',
    it: 'segnalato dal daemon in esecuzione',
    de: 'vom laufenden daemon gemeldet',
    ja: '実行中のデーモンから取得',
    zh: '来自正在运行的守护进程',
  },
  sourceCli: {
    en: 'this CLI, daemon not reachable',
    es: 'esta CLI; el daemon no responde',
    fr: 'cette CLI, daemon injoignable',
    it: 'questa CLI, daemon non raggiungibile',
    de: 'diese CLI, daemon nicht erreichbar',
    ja: '本 CLI から取得、デーモンには未接続',
    zh: '来自本 CLI，未连接守护进程',
  },

  // ---- daemon ---------------------------------------------------------------
  daemonStartForeground: {
    en: 'ship daemon ready (pid {pid}), listening on {socket}.',
    es: 'daemon de ship listo (pid {pid}), escuchando en {socket}.',
    fr: 'daemon ship prêt (pid {pid}), à l\'écoute sur {socket}.',
    it: 'daemon di ship pronto (pid {pid}), in ascolto su {socket}.',
    de: 'ship-daemon bereit (pid {pid}), lauscht auf {socket}.',
    ja: 'ship デーモンの準備ができました（pid {pid}）。{socket} で待ち受けています。',
    zh: 'ship 守护进程已就绪（pid {pid}），正在监听 {socket}。',
  },
  daemonStartForegroundHint: {
    en: 'this process runs in the foreground -- ctrl+c to stop, or run it with & to background it.',
    es: 'este proceso se ejecuta en primer plano; pulsa ctrl+c para detenerlo, o inícialo con & para dejarlo en segundo plano.',
    fr: 'ce processus s\'exécute au premier plan -- ctrl+c pour l\'arrêter, ou lancez-le avec & pour le mettre en arrière-plan.',
    it: 'questo processo viene eseguito in primo piano: premi ctrl+c per interromperlo, oppure avvialo con & per metterlo in background.',
    de: 'dieser prozess läuft im vordergrund -- strg+c zum beenden, oder starte ihn mit & im hintergrund.',
    ja: 'このプロセスはフォアグラウンドで動作しています。停止するには ctrl+c を押すか、末尾に & を付けて実行するとバックグラウンド化できます。',
    zh: '此进程在前台运行 —— 按 ctrl+c 停止，或在命令末尾加 & 使其转入后台运行。',
  },
  daemonStartVerboseHint: {
    en: '--dev: Block lifecycle, IPC, and health-check activity will print below as it happens.',
    es: '--dev: la actividad del ciclo de vida de los Block, la IPC y las comprobaciones de estado se mostrará a continuación en tiempo real.',
    fr: '--dev : l\'activité du cycle de vie des Block, de l\'IPC et des contrôles de santé s\'affichera ci-dessous en temps réel.',
    it: '--dev: l\'attività del ciclo di vita dei Block, dell\'IPC e dei controlli di stato verrà mostrata qui sotto in tempo reale.',
    de: '--dev: Block-lebenszyklus-, IPC- und health-check-aktivität wird unten in echtzeit angezeigt.',
    ja: '--dev: Block のライフサイクル、IPC、ヘルスチェックの動作がこの下にリアルタイムで表示されます。',
    zh: '--dev：Block 生命周期、IPC 与健康检查的活动将实时打印在下面。',
  },
  daemonInstallSuccess: {
    en: 'installed and started ({mechanism}). ship will now launch automatically, even after a restart.',
    es: 'instalado e iniciado ({mechanism}). ship se iniciará automáticamente a partir de ahora, incluso tras reiniciar.',
    fr: 'installé et démarré ({mechanism}). ship se lancera désormais automatiquement, même après un redémarrage.',
    it: 'installato e avviato ({mechanism}). da ora ship si avvierà automaticamente, anche dopo un riavvio.',
    de: 'installiert und gestartet ({mechanism}). ship startet ab jetzt automatisch, auch nach einem neustart.',
    ja: 'インストールと起動が完了しました（{mechanism}）。これ以降、再起動後も ship は自動的に起動します。',
    zh: '已安装并启动（{mechanism}）。此后 ship 将自动启动，即使重启电脑也是如此。',
  },
  daemonUninstallSuccess: {
    en: 'removed. ship will no longer start automatically.',
    es: 'eliminado. ship ya no se iniciará automáticamente.',
    fr: 'supprimé. ship ne démarrera plus automatiquement.',
    it: 'rimosso. ship non si avvierà più automaticamente.',
    de: 'entfernt. ship startet nicht mehr automatisch.',
    ja: '削除しました。今後 ship は自動的には起動しません。',
    zh: '已移除。ship 将不再自动启动。',
  },
  daemonStopSuccess: {
    en: 'told the daemon to shut down.',
    es: 'se indicó al daemon que se detuviera.',
    fr: 'le daemon a reçu l\'ordre de s\'arrêter.',
    it: 'al daemon è stato chiesto di arrestarsi.',
    de: 'der daemon wurde zum beenden aufgefordert.',
    ja: 'デーモンに停止するよう指示しました。',
    zh: '已通知守护进程关闭。',
  },
  daemonStatusRunning: {
    en: 'the daemon is running.',
    es: 'el daemon está en ejecución.',
    fr: 'le daemon est en cours d\'exécution.',
    it: 'il daemon è in esecuzione.',
    de: 'der daemon läuft.',
    ja: 'デーモンは起動中です。',
    zh: '守护进程正在运行。',
  },
  daemonStatusStopped: {
    en: 'the daemon is not running.',
    es: 'el daemon no está en ejecución.',
    fr: 'le daemon n\'est pas en cours d\'exécution.',
    it: 'il daemon non è in esecuzione.',
    de: 'der daemon läuft nicht.',
    ja: 'デーモンは停止しています。',
    zh: '守护进程未运行。',
  },

  // ---- logs -------------------------------------------------------------
  logsHeaderDaemon: {
    en: 'last {count} daemon log lines:',
    es: 'últimas {count} líneas del registro del daemon:',
    fr: 'dernières {count} lignes du journal du daemon :',
    it: 'ultime {count} righe del registro del daemon:',
    de: 'letzte {count} zeilen des daemon-protokolls:',
    ja: 'デーモンログの直近{count}行:',
    zh: '守护进程日志的最近 {count} 行：',
  },
  logsHeaderBlock: {
    en: 'last {count} log lines for {app} : {block}:',
    es: 'últimas {count} líneas de {app} : {block}:',
    fr: 'dernières {count} lignes pour {app} : {block} :',
    it: 'ultime {count} righe per {app} : {block}:',
    de: 'letzte {count} zeilen für {app} : {block}:',
    ja: '{app} : {block} の直近{count}行:',
    zh: '{app} : {block} 的最近 {count} 行日志：',
  },
  logsEmpty: {
    en: 'no log lines yet.',
    es: 'todavía no hay líneas de registro.',
    fr: 'aucune ligne de journal pour le moment.',
    it: 'ancora nessuna riga di log.',
    de: 'noch keine protokollzeilen.',
    ja: 'まだログはありません。',
    zh: '目前还没有日志。',
  },

  // ---- vault --------------------------------------------------------------
  vaultExportPrompt: {
    en: 'Vault export passphrase',
    es: 'frase de contraseña para exportar el Vault',
    fr: 'phrase secrète pour l\'export du Vault',
    it: 'passphrase per l\'esportazione del Vault',
    de: 'passphrase für den Vault-export',
    ja: 'Vault エクスポート用のパスフレーズ',
    zh: 'Vault 导出密码短语',
  },
  vaultImportPrompt: {
    en: 'Vault import passphrase',
    es: 'frase de contraseña para importar el Vault',
    fr: 'phrase secrète pour l\'import du Vault',
    it: 'passphrase per l\'importazione del Vault',
    de: 'passphrase für den Vault-import',
    ja: 'Vault インポート用のパスフレーズ',
    zh: 'Vault 导入密码短语',
  },
  vaultExportSuccess: {
    en: 'Vault exported to {path}. keep this file and its passphrase safe -- together they unlock every secret in it.',
    es: 'Vault exportado a {path}. guarda este archivo y su frase de contraseña en un lugar seguro: juntos permiten desbloquear todos los secretos que contiene.',
    fr: 'Vault exporté vers {path}. conservez ce fichier et sa phrase secrète en lieu sûr -- ensemble, ils déverrouillent tous les secrets qu\'il contient.',
    it: 'Vault esportato in {path}. conserva questo file e la sua passphrase in un luogo sicuro: insieme sbloccano tutti i segreti al suo interno.',
    de: 'Vault exportiert nach {path}. bewahre diese datei und ihre passphrase sicher auf -- zusammen entsperren sie jedes darin enthaltene geheimnis.',
    ja: 'Vault を {path} にエクスポートしました。このファイルとパスフレーズは大切に保管してください。両方揃うと中のすべてのシークレットを復号できます。',
    zh: 'Vault 已导出到 {path}。请妥善保管此文件及其密码短语 —— 两者结合可以解锁其中的所有密钥。',
  },
  vaultImportSuccess: {
    en: 'Vault imported from {path}.',
    es: 'Vault importado desde {path}.',
    fr: 'Vault importé depuis {path}.',
    it: 'Vault importato da {path}.',
    de: 'Vault importiert aus {path}.',
    ja: '{path} から Vault をインポートしました。',
    zh: '已从 {path} 导入 Vault。',
  },
  vaultWrongPassphrase: {
    en: 'that passphrase didn\'t work -- either it\'s wrong, or the file is corrupted.',
    es: 'esa frase de contraseña no funcionó: o es incorrecta, o el archivo está dañado.',
    fr: 'cette phrase secrète n\'a pas fonctionné -- soit elle est incorrecte, soit le fichier est corrompu.',
    it: 'questa passphrase non ha funzionato: o è sbagliata, o il file è danneggiato.',
    de: 'diese passphrase hat nicht funktioniert -- entweder ist sie falsch, oder die datei ist beschädigt.',
    ja: 'そのパスフレーズでは復号できませんでした。パスフレーズが間違っているか、ファイルが破損しています。',
    zh: '该密码短语无效 —— 要么密码错误，要么文件已损坏。',
  },

  // ---- login --------------------------------------------------------------
  loginEmailPrompt: {
    en: 'email',
    es: 'correo electrónico',
    fr: 'e-mail',
    it: 'email',
    de: 'e-mail',
    ja: 'メールアドレス',
    zh: '电子邮箱',
  },
  loginPasswordPrompt: {
    en: 'password',
    es: 'contraseña',
    fr: 'mot de passe',
    it: 'password',
    de: 'passwort',
    ja: 'パスワード',
    zh: '密码',
  },
  loginSuccess: {
    en: 'signed in as {email}.',
    es: 'sesión iniciada como {email}.',
    fr: 'connecté en tant que {email}.',
    it: 'accesso effettuato come {email}.',
    de: 'angemeldet als {email}.',
    ja: '{email} としてサインインしました。',
    zh: '已以 {email} 身份登录。',
  },

  // ---- new / import ---------------------------------------------------------
  newSuccess: {
    en: 'created "{name}" at {path}. next: cd into it and run "ship deploy".',
    es: 'se creó "{name}" en {path}. siguiente paso: entra con cd y ejecuta "ship deploy".',
    fr: '« {name} » créé dans {path}. prochaine étape : allez-y avec cd puis lancez « ship deploy ».',
    it: '"{name}" creato in {path}. prossimo passo: entra con cd ed esegui "ship deploy".',
    de: '„{name}“ wurde in {path} erstellt. nächster schritt: mit cd hineinwechseln und „ship deploy“ ausführen.',
    ja: '{path} に "{name}" を作成しました。次は cd で移動して「ship deploy」を実行してください。',
    zh: '已在 {path} 创建 "{name}"。下一步：cd 进入该目录并运行 "ship deploy"。',
  },
  importSuccess: {
    en: 'imported "{name}" into {path} -- detected {framework}.',
    es: 'se importó "{name}" en {path}: se detectó {framework}.',
    fr: '« {name} » importé dans {path} -- {framework} détecté.',
    it: '"{name}" importato in {path}: rilevato {framework}.',
    de: '„{name}“ wurde nach {path} importiert -- erkannt: {framework}.',
    ja: '{path} に "{name}" をインポートしました。検出されたフレームワーク: {framework}。',
    zh: '已将 "{name}" 导入到 {path} —— 检测到 {framework}。',
  },
  importSuccessExistingConfig: {
    en: 'imported "{name}" into {path} -- using its existing ship.config.js as-is.',
    es: 'se importó "{name}" en {path}: se utiliza su ship.config.js existente tal cual.',
    fr: '« {name} » importé dans {path} -- utilise son ship.config.js existant tel quel.',
    it: '"{name}" importato in {path}: viene utilizzato il suo ship.config.js esistente così com\'è.',
    de: '„{name}“ wurde nach {path} importiert -- die vorhandene ship.config.js wird unverändert übernommen.',
    ja: '{path} に "{name}" をインポートしました。既存の ship.config.js をそのまま使用します。',
    zh: '已将 "{name}" 导入到 {path} —— 直接使用其原有的 ship.config.js。',
  },
  importNoteLabel: {
    en: 'note',
    es: 'nota',
    fr: 'remarque',
    it: 'nota',
    de: 'hinweis',
    ja: '補足',
    zh: '提示',
  },

  // ---- deploy / stop ------------------------------------------------------
  deploySuccess: {
    en: 'deployed "{app}" ({mode}). live at {url}.',
    es: 'se implementó "{app}" ({mode}). disponible en {url}.',
    fr: '« {app} » déployé ({mode}). en ligne sur {url}.',
    it: '"{app}" distribuito ({mode}). disponibile su {url}.',
    de: '„{app}“ wurde bereitgestellt ({mode}). live unter {url}.',
    ja: '"{app}" をデプロイしました（{mode}）。{url} で公開中です。',
    zh: '"{app}" 已部署（{mode}）。访问地址：{url}。',
  },
  modePost: {
    en: 'local', es: 'local', fr: 'local', it: 'locale', de: 'lokal', ja: 'ローカル', zh: '本地',
  },
  modePreview: {
    en: 'preview', es: 'vista previa', fr: 'aperçu', it: 'anteprima', de: 'vorschau', ja: 'プレビュー', zh: '预览',
  },
  modeProduction: {
    en: 'production', es: 'producción', fr: 'production', it: 'produzione', de: 'produktion', ja: '本番環境', zh: '生产环境',
  },
  stopSuccess: {
    en: 'stopped "{app}".',
    es: 'se detuvo "{app}".',
    fr: '« {app} » arrêté.',
    it: '"{app}" arrestato.',
    de: '„{app}“ wurde gestoppt.',
    ja: '"{app}" を停止しました。',
    zh: '"{app}" 已停止。',
  },
  stopBlockSuccess: {
    en: 'stopped "{block}" in "{app}".',
    es: 'se detuvo "{block}" en "{app}".',
    fr: '« {block} » arrêté dans « {app} ».',
    it: '"{block}" arrestato in "{app}".',
    de: '„{block}“ in „{app}“ wurde gestoppt.',
    ja: '"{app}" の "{block}" を停止しました。',
    zh: '已停止 "{app}" 中的 "{block}"。',
  },
  deployDomainMissing: {
    en: 'production deploys need a domain: ship deploy production <app> --domain=<your-domain>',
    es: 'las implementaciones de producción necesitan un dominio: ship deploy production <app> --domain=<tu-dominio>',
    fr: 'les déploiements de production nécessitent un domaine : ship deploy production <app> --domain=<votre-domaine>',
    it: 'le distribuzioni in produzione richiedono un dominio: ship deploy production <app> --domain=<tuo-dominio>',
    de: 'produktions-deployments benötigen eine domain: ship deploy production <app> --domain=<deine-domain>',
    ja: '本番環境へのデプロイにはドメインが必要です: ship deploy production <app> --domain=<あなたのドメイン>',
    zh: '生产环境部署需要指定域名：ship deploy production <app> --domain=<你的域名>',
  },
  deployAlreadyRunning: {
    en: '"{app}" is already deployed. stop it first with "ship stop {app}".',
    es: '"{app}" ya está implementado. detenlo primero con "ship stop {app}".',
    fr: '« {app} » est déjà déployé. arrêtez-le d\'abord avec « ship stop {app} ».',
    it: '"{app}" è già distribuito. fermalo prima con "ship stop {app}".',
    de: '„{app}“ ist bereits bereitgestellt. stoppe es zuerst mit „ship stop {app}“.',
    ja: '"{app}" はすでにデプロイされています。先に「ship stop {app}」で停止してください。',
    zh: '"{app}" 已经在运行。请先运行 "ship stop {app}" 停止它。',
  },
  deployTimedOut: {
    en: 'timed out waiting for the daemon to finish. it may still be working -- check with "ship logs".',
    es: 'se agotó el tiempo esperando a que el daemon terminara. puede que siga trabajando: revísalo con "ship logs".',
    fr: 'délai dépassé en attendant que le daemon termine. il travaille peut-être encore -- vérifiez avec « ship logs ».',
    it: 'tempo scaduto in attesa che il daemon terminasse. potrebbe essere ancora al lavoro: controlla con "ship logs".',
    de: 'zeitüberschreitung beim warten auf den daemon. er arbeitet möglicherweise noch -- prüfe mit „ship logs“.',
    ja: 'デーモンの完了待ちがタイムアウトしました。まだ処理中の可能性があります。「ship logs」で確認してください。',
    zh: '等待守护进程完成时超时。它可能仍在处理中 —— 可用 "ship logs" 查看。',
  },

  // ---- connectors ---------------------------------------------------------
  connectorInstallSuccess: {
    en: 'installed "{name}".',
    es: 'se instaló "{name}".',
    fr: '« {name} » installé.',
    it: '"{name}" installato.',
    de: '„{name}“ installiert.',
    ja: '"{name}" をインストールしました。',
    zh: '已安装 "{name}"。',
  },
  connectorUninstallSuccess: {
    en: 'uninstalled "{name}".',
    es: 'se desinstaló "{name}".',
    fr: '« {name} » désinstallé.',
    it: '"{name}" disinstallato.',
    de: '„{name}“ deinstalliert.',
    ja: '"{name}" をアンインストールしました。',
    zh: '已卸载 "{name}"。',
  },
  connectorPublishSuccess: {
    en: 'published {name}@{version}.',
    es: 'se publicó {name}@{version}.',
    fr: '{name}@{version} publié.',
    it: '{name}@{version} pubblicato.',
    de: '{name}@{version} veröffentlicht.',
    ja: '{name}@{version} を公開しました。',
    zh: '已发布 {name}@{version}。',
  },
  connectorListEmpty: {
    en: 'no connectors installed.',
    es: 'no hay conectores instalados.',
    fr: 'aucun connecteur installé.',
    it: 'nessun connettore installato.',
    de: 'keine connectors installiert.',
    ja: 'インストール済みのコネクタはありません。',
    zh: '未安装任何连接器。',
  },
  connectorListHeader: {
    en: 'installed connectors:',
    es: 'conectores instalados:',
    fr: 'connecteurs installés :',
    it: 'connettori installati:',
    de: 'installierte connectors:',
    ja: 'インストール済みのコネクタ:',
    zh: '已安装的连接器：',
  },

  // ---- help -----------------------------------------------------------------
  helpTitle: {
    en: 'ship -- commands',
    es: 'ship: comandos',
    fr: 'ship -- commandes',
    it: 'ship: comandi',
    de: 'ship -- befehle',
    ja: 'ship — コマンド一覧',
    zh: 'ship —— 命令列表',
  },
  helpCmdStartup: {
    en: 'set up your language and how the daemon runs',
    es: 'configura tu idioma y cómo se ejecuta el daemon',
    fr: 'configure votre langue et le mode de fonctionnement du daemon',
    it: 'configura la tua lingua e la modalità di esecuzione del daemon',
    de: 'richtet deine sprache und die ausführungsart des daemons ein',
    ja: '言語とデーモンの実行方法を設定します',
    zh: '设置你的语言以及守护进程的运行方式',
  },
  helpCmdDaemonStart: {
    en: 'run the daemon in this terminal',
    es: 'ejecuta el daemon en esta terminal',
    fr: 'exécute le daemon dans ce terminal',
    it: 'esegue il daemon in questo terminale',
    de: 'startet den daemon in diesem terminal',
    ja: 'このターミナルでデーモンを実行します',
    zh: '在当前终端中运行守护进程',
  },
  helpCmdDaemonInstall: {
    en: 'install the daemon as a background service',
    es: 'instala el daemon como servicio en segundo plano',
    fr: 'installe le daemon en tant que service en arrière-plan',
    it: 'installa il daemon come servizio in background',
    de: 'installiert den daemon als hintergrunddienst',
    ja: 'デーモンをバックグラウンドサービスとしてインストールします',
    zh: '将守护进程安装为后台服务',
  },
  helpCmdDaemonUninstall: {
    en: 'remove the background service',
    es: 'elimina el servicio en segundo plano',
    fr: 'supprime le service en arrière-plan',
    it: 'rimuove il servizio in background',
    de: 'entfernt den hintergrunddienst',
    ja: 'バックグラウンドサービスを削除します',
    zh: '移除后台服务',
  },
  helpCmdDaemonStop: {
    en: 'shut the daemon down',
    es: 'detiene el daemon',
    fr: 'arrête le daemon',
    it: 'arresta il daemon',
    de: 'beendet den daemon',
    ja: 'デーモンを停止します',
    zh: '关闭守护进程',
  },
  helpCmdDaemonStatus: {
    en: 'check whether the daemon is running',
    es: 'comprueba si el daemon está en ejecución',
    fr: 'vérifie si le daemon est en cours d\'exécution',
    it: 'verifica se il daemon è in esecuzione',
    de: 'prüft, ob der daemon läuft',
    ja: 'デーモンが起動しているか確認します',
    zh: '检查守护进程是否正在运行',
  },
  helpCmdVersion: {
    en: 'show the installed version',
    es: 'muestra la versión instalada',
    fr: 'affiche la version installée',
    it: 'mostra la versione installata',
    de: 'zeigt die installierte version',
    ja: 'インストール済みのバージョンを表示します',
    zh: '显示已安装的版本',
  },
  helpCmdNew: {
    en: 'scaffold a new App',
    es: 'crea la estructura de una nueva App',
    fr: 'crée la structure d\'une nouvelle App',
    it: 'genera la struttura di una nuova App',
    de: 'legt eine neue App an',
    ja: '新しいアプリの雛形を作成します',
    zh: '创建一个新应用的初始结构',
  },
  helpCmdImport: {
    en: 'bring in an existing App (git URL, local path, or archive)',
    es: 'importa una App existente (URL de git, ruta local o archivo comprimido)',
    fr: 'importe une App existante (URL git, chemin local ou archive)',
    it: 'importa un\'App esistente (URL git, percorso locale o archivio)',
    de: 'importiert eine bestehende App (git-URL, lokaler pfad oder archiv)',
    ja: '既存のアプリを取り込みます（git の URL、ローカルパス、アーカイブに対応）',
    zh: '导入一个已有的应用（支持 git 地址、本地路径或压缩包）',
  },
  helpCmdDeploy: {
    en: 'deploy an App locally',
    es: 'implementa una App de forma local',
    fr: 'déploie une App en local',
    it: 'distribuisce un\'App in locale',
    de: 'stellt eine App lokal bereit',
    ja: 'アプリをローカルにデプロイします',
    zh: '在本地部署应用',
  },
  helpCmdProduction: {
    en: 'deploy an App to your own domain',
    es: 'implementa una App en tu propio dominio',
    fr: 'déploie une App sur votre propre domaine',
    it: 'distribuisce un\'App sul tuo dominio',
    de: 'stellt eine App unter deiner eigenen domain bereit',
    ja: '自分のドメインにアプリをデプロイします',
    zh: '将应用部署到你自己的域名下',
  },
  helpCmdStop: {
    en: 'stop a deployed App (or one of its Blocks)',
    es: 'detiene una App implementada (o uno de sus Blocks)',
    fr: 'arrête une App déployée (ou l\'un de ses Blocks)',
    it: 'arresta un\'App distribuita (o uno dei suoi Block)',
    de: 'stoppt eine bereitgestellte App (oder einen ihrer Blocks)',
    ja: 'デプロイ済みのアプリ（またはその一部の Block）を停止します',
    zh: '停止一个已部署的应用（或其中的某个 Block）',
  },
  helpCmdLogs: {
    en: 'show recent log lines',
    es: 'muestra las líneas de registro recientes',
    fr: 'affiche les lignes de journal récentes',
    it: 'mostra le righe di log recenti',
    de: 'zeigt die letzten protokollzeilen',
    ja: '最近のログを表示します',
    zh: '显示最近的日志',
  },
  helpCmdVaultExport: {
    en: 'export an encrypted backup of your secrets',
    es: 'exporta una copia de seguridad cifrada de tus secretos',
    fr: 'exporte une sauvegarde chiffrée de vos secrets',
    it: 'esporta un backup crittografato dei tuoi segreti',
    de: 'exportiert eine verschlüsselte sicherung deiner secrets',
    ja: 'シークレットの暗号化バックアップをエクスポートします',
    zh: '导出加密的密钥备份',
  },
  helpCmdVaultImport: {
    en: 'restore secrets from a backup',
    es: 'restaura secretos desde una copia de seguridad',
    fr: 'restaure des secrets depuis une sauvegarde',
    it: 'ripristina i segreti da un backup',
    de: 'stellt secrets aus einer sicherung wieder her',
    ja: 'バックアップからシークレットを復元します',
    zh: '从备份中恢复密钥',
  },
  helpCmdLogin: {
    en: 'sign in (needed for preview deploys)',
    es: 'inicia sesión (necesario para implementaciones de vista previa)',
    fr: 'connectez-vous (nécessaire pour les déploiements aperçu)',
    it: 'accedi (necessario per le distribuzioni in anteprima)',
    de: 'anmelden (für vorschau-deployments erforderlich)',
    ja: 'サインインします（プレビューへのデプロイに必要です）',
    zh: '登录（预览部署需要登录）',
  },
  helpCmdConnectorInstall: {
    en: 'install a connector',
    es: 'instala un conector',
    fr: 'installe un connecteur',
    it: 'installa un connettore',
    de: 'installiert einen connector',
    ja: 'コネクタをインストールします',
    zh: '安装一个连接器',
  },
  helpCmdConnectorUninstall: {
    en: 'remove a connector',
    es: 'elimina un conector',
    fr: 'supprime un connecteur',
    it: 'rimuove un connettore',
    de: 'entfernt einen connector',
    ja: 'コネクタを削除します',
    zh: '移除一个连接器',
  },
  helpCmdConnectorList: {
    en: 'list installed connectors',
    es: 'muestra los conectores instalados',
    fr: 'liste les connecteurs installés',
    it: 'elenca i connettori installati',
    de: 'listet installierte connectors auf',
    ja: 'インストール済みのコネクタを一覧表示します',
    zh: '列出已安装的连接器',
  },
  helpCmdConnectorPublish: {
    en: 'publish a connector to the registry',
    es: 'publica un conector en el registro',
    fr: 'publie un connecteur sur le registre',
    it: 'pubblica un connettore nel registro',
    de: 'veröffentlicht einen connector in der registry',
    ja: 'コネクタをレジストリに公開します',
    zh: '将连接器发布到注册中心',
  },
  helpCmdHelp: {
    en: 'show this list',
    es: 'muestra esta lista',
    fr: 'affiche cette liste',
    it: 'mostra questo elenco',
    de: 'zeigt diese liste',
    ja: 'この一覧を表示します',
    zh: '显示此列表',
  },
};

export function t(locale, key, params = {}) {
  const entry = STRINGS[key];
  if (!entry) return key;
  const template = entry[locale] ?? entry.en ?? key;
  return template.replace(/\{(\w+)\}/g, (match, name) => (params[name] !== undefined ? String(params[name]) : match));
}
